# Site settings
title: Box Of Bolts
email: yoadsn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yoad Snapir's blog, Hosting my random bolts of thought.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.boxofbolts.com" # the base hostname & protocol for your site
permalink: pretty
twitter_username: ysnapir
github_username:  yoadsn

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'boxofbolts'
comments: true

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-64738582-1'

# Build settings
markdown: kramdown
